BASE_URL = "https://www.tobeto.com"
LOGIN_URL = "https://tobeto.com/giris"
firstLoginButton = ".border-light"
emailName = "email"
passwordName = "password"
loginButton = "//button[@class='btn btn-primary w-100 mt-6']"
loginMessage = "div[class='toast-body']"
beginButton = "div[class='details pack-bg-2']>button[class='btn btn-primary w-100 ']"
educationLink = "div[class='p-2 py-4 mobile-sidebar']>a[class='btn mb-2 text-start w-100  sidebar-link ']:nth-child(3) span[class='sidebar-text']"
saveButton = "button[class='btn btn-primary py-2 mb-3 d-inline-block mobil-btn']"
expectedResultempty = "span[class='text-danger']"
selectEducationDropdown = "select[name='EducationStatus']"
enterUniversity = "input[name='University']"
departmentName = "input[name='Department']"
graduationYear = "input[class='form-control tobeto-input ']"
beginDate = "div[class='react-datepicker__input-container ']>input[class='form-control tobeto-input']"
dateCalendar = "div[class='react-datepicker__year-text react-datepicker__year-text--keyboard-selected react-datepicker__year-text--today']"
continueCss = "input[name='checkbox']"
expectedResultCss = "div[class='toast-body']"

