LOGIN_URL="https://tobeto.com/giris"
userEmail = "email"
userPassword = "password"
LOGIN_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
homePage = "//*[@id='__next']/div/nav/div[1]/ul/li[1]/a"
myProfile =  "//*[@id='__next']/div/nav/div[1]/ul/li[2]/a"
reviews = "//*[@id='__next']/div/nav/div[1]/ul/li[3]/a"
catalog = "//*[@id='__next']/div/nav/div[1]/ul/li[4]/a"
calender = "//*[@id='__next']/div/nav/div[1]/ul/li[5]/a"
istanbul_kodluyor = "//*[@id='__next']/div/nav/div[1]/ul/li[6]/a"