LOGIN_URL="https://tobeto.com/giris"
EDUCATION_URL="https://tobeto.com/egitimlerim"
NAME_TAG = "email"
PSW_TAG = "password"
login_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
myEducations_id = "lessons-tab"
showMoreButton="//div[@class='showMoreBtn'][1]"
search_id = "search"
education_xpath = "//*[@id='all-lessons-tab-pane']/div/p"
institution_xpath = '//*[@id="__next"]/div/main/div[2]/div[1]/div/div[2]/div/div[1]'
istanbulKodluyor_id = "react-select-2-listbox"
continue_xpath = "//*[@id='myTab']/li[2]"
allEducations_xpath = "//*[@id='myTab']/li[1]"
completedEducations_xpath = "//*[@id='myTab']/li[3]"
deleteFilter="/html/body/div[1]/div/main/div[2]/div[1]/div/div[4]/button"
listButton_xpath= "//div[3]/div/div/div[2]/div"
listE_Y_id="react-select-3-option-3"
listY_E_id="react-select-3-option-2"
listZ_A_id="react-select-3-option-1"
listA_Z_id="react-select-3-option-0"